### PR TITLE
Make recipe noarch

### PR DESCRIPTION
**Pull request by ericpre**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [n/a] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [n/a] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ericpre** [comment]
Use https://github.com/conda-forge/conda-forge.github.io/pull/1839 and https://github.com/conda-forge/constructor-feedstock/pull/63 as reference.

The linter message can be ignored because it is now possible to have selectors with noarch package.

**Review by hakonanes — APPROVED** [review]
That's great @ericpre, thank you for taking the time to do this.

We state in [the installation guide](https://pyebsdindex.readthedocs.io/en/latest/installation.html#with-conda) that Jupyterlab is automatically installed with conda. We should remove this after this is merged.

I'll leave it up to @drowenhorst-nrl to merge when he's happy.

**Comment by ericpre** [comment]
Yes, with this PR, the installation instruction can be simplified.

This is currently holding new releases of the hyperspy bundle because `kikuchipy` added 
`pyebsdindex-base` as dependency and the packages for osx-arm64 are missing.

**Review by drowenhorst-nrl — APPROVED** [review]

**Comment by hakonanes** [comment]
> This is currently holding new releases of the hyperspy bundle because kikuchipy added pyebsdindex-base as dependency

Aha... Estimation of orientations and projection centers via Hough indexing in PyEBSDIndex is instrumental to the usefulness of kikuchipy. Again, thank you for taking the time to help with the release of PyEBSDIndex.

**Comment by ericpre** [comment]
This noarch approach is quite new but I have tested the new package on various platform (win, linux, osx_arm64) and from what I can tell by running the pyebsdindex test suite the change of this PR seems to work as expected! :)
This is quite useful because it would save the migration to other platforms or new python versions.

**Pull request merged**
